#ifndef _TCPIP_PROJECT_CMDCODES_H_
#define _TCPIP_PROJECT_CMDCODES_H_

enum CMDCODES {
	CMDCODES_SHOW_TOPOLOGY = 1,
	CMDCODES_RUN_NODE_RESOLVE_ARP,
	CMDCODES_END_OF_ENUM
};

#endif // _TCPIP_PROJECT_CMDCODES_H_
